require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Firebase
$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TaskManager' do
  config = use_native_modules!

  # Required for Firebase
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        unless target.name == 'fmt'
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
        end

        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION'
        ]
      end

      if target.name == 'fmt'
        target.build_configurations.each do |build_config|
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end